apiVersion: v1
kind: Service
metadata:
  name: fintrack-notification-service
  namespace: fintrack
spec:
  type: NodePort
  selector:
    app: fintrack-notification-service
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8087
      targetPort: 8087
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32087
