apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-web-push-service
  namespace: fintrack
  labels:
    app: fintrack-web-push-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fintrack-web-push-service
  template:
    metadata:
      labels:
        app: fintrack-web-push-service
    spec:
      containers:
        - name: fintrack-web-push-service
          image: kimheang68/fintrack-web-push-service:latest
          ports:
            - containerPort: 8084
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
