apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-aos-service
  namespace: fintrack
  labels:
    app: fintrack-aos-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fintrack-aos-service
  template:
    metadata:
      labels:
        app: fintrack-aos-service
    spec:
      containers:
      - name: fintrack-aos-service
        image: kimheang68/fintrack-aos-service:4
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/fintrack-aos-service"
        
