apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-ui
spec:
  selector:
    matchLabels:
      app: fintrack-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: fintrack-ui
    spec:
      containers:
      - name: fintrack-ui
        image: kimheang68/ui-fintrack:17
        args:
        - "-text=fintrack-ui"
        ports:
        - containerPort: 80