apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintrack-ui
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - fintrack.kbaenak.tech
    secretName: web-fintrack-cert
  rules:
    - host: fintrack.kbaenak.tech
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: fintrack-ui
                port:
                  number: 1080
    