apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintrack-ui-ingress
  namespace: fintrack
  labels:
    app: fintrack-ui
spec:
  rules:
    - host: web-fintrack.kbaenak.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fintrack-ui-service
                port:
                  number: 80
