apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintrack-ui
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - failtrack.kbaenak.tech
    secretName: app-tls
  rules:
    - host: failtrack.kbaenak.tech
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: fintrack-ui
                port:
                  number: 1080
    