apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-email-kb-service
  namespace: fintrack
  labels:
    app: fintrack-email-kb-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fintrack-email-kb-service
  template:
    metadata:
      labels:
        app: fintrack-email-kb-service
    spec:
      containers:
        - name: fintrack-email-kb-service
          image: kimheang68/fintrack-email-kb-service:29
          ports:
            - containerPort: 8085
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
