apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintrack
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-fintrack"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - web-fintrack.kbaenak.tech
    secretName: fintrack-cert-app
  rules:
    - host: web-fintrack.kbaenak.tech
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: fintrack-ui
                port:
                  number: 1080
    