apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fintrack-cert-app
  namespace: fintrack
spec:
  dnsNames:
    - www.fintrack.dev
    - api.fintrack.dev
    - web.seiha.lol
    - fintrack.dev
    
  secretName: app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer