apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintrack
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-fintrack"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - web-fintrack.kbaenak.tech
    - api-fintrack.kbaenak.tech
    secretName: fintrack-cert-app
  rules:
    # DNS UI
    - host: web-fintrack.kbaenak.tech
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: fintrack-ui
                port:
                  number: 1080
    # DNS API
    - host: api-fintrack.kbaenak.tech
      http:
        paths:

          # Authentication-Service
          - pathType: Prefix
            path: "/fintrack-authentication-service"
            backend:
              service:
                name: fintrack-authentication-service
                port:
                  number: 8081
          # Client-Event-Service
          - pathType: Prefix
            path: "/fintrack-client-event-service"
            backend:
              service:
                name: fintrack-client-event-service
                port:
                  number: 8088
          # Web-Push-Service
          - pathType: Prefix
            path: "/fintrack-web-push-service"
            backend:
              service:
                name: fintrack-web-push-service
                port:
                  number: 8084
          # Scheduler
          - pathType: Prefix
            path: "/fintrack-scheduler-service"
            backend:
              service:
                name: fintrack-scheduler-service
                port:
                  number: 8086
          
    