apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fintrack-cert-app
  namespace: fintrack
spec:
  dnsNames:
    # - api.fintrack.dev
    # - fintrack.dev
    - fintrack.kbaenak.tech
    - api-fintrack.kbaenak.tech
    
  secretName: app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
