apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fintrack-cert-app
  namespace: fintrack
spec:
  dnsNames:
    - web-fintrack.kbaenak.tech
    - api-fintrack.kbaenak.tech
    - web.seiha.lol
  secretName: app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer