---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: fintrack
  name: fintrack-telegram-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fintrack-telegram-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
...